"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# MONKEY-PATCH: Fix compatibility issue between django_mongodb_backend 6.0.2+ and pymongo 4.7+
# where the backend tries to access the removed `_options` attribute.
import pymongo
if not hasattr(pymongo.MongoClient, '_options'):
    pymongo.MongoClient._options = property(lambda self: self.options)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ruo=byp3o1-y@9l^m_)2f*gody6k=q4jng01u#_o^ea$zpd$v-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'authentication.apps.AuthenticationConfig',
    'reels',
    'comments',
    'analysis',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os
from dotenv import load_dotenv

load_dotenv(BASE_DIR / '.env')

MONGODB_URI = os.getenv('MONGODB_URI')
if not MONGODB_URI:
    raise ValueError("MONGODB_URI environment variable is not set. Check your .env file.")

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': 'giveaway_db',
        'HOST': MONGODB_URI,
        'CONN_MAX_AGE': 600,
    }
}




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'

AUTH_USER_MODEL = 'authentication.User'

SILENCED_SYSTEM_CHECKS = ['models.W042', 'fields.W042', 'mongodb.E001']

# Disable Django built-in app migrations — they use integer AutoField which
# conflicts with MongoDB ObjectId during post_migrate permission creation.
MIGRATION_MODULES = {
    'contenttypes': None,
    'auth': None,
    'admin': None,
    'sessions': None,
}

CORS_ALLOW_ALL_ORIGINS = True
APPEND_SLASH = False

JAZZMIN_SETTINGS = {
    "site_title": "Giveaway Admin",
    "site_header": "Giveaway Picker",
    "site_brand": "ReelAnalyzer",
    "welcome_sign": "Welcome to Giveaway-Winner-Picker Admin",
    "copyright": "ReelAnalyzer Ltd",
    "search_model": ["auth.User", "authentication.InstagramProfile"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "authentication.InstagramProfile": "fab fa-instagram",
        "reels.Reel": "fas fa-video",
        "comments.Comment": "fas fa-comments",
    },
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "https://giveaway-winner-picker.vercel.app", "new_window": True},
    ],
    "order_with_respect_to": ["authentication", "reels", "comments", "auth"],
    "theme": "flatly",
    "dark_mode_theme": "darkly",
}
