# Generated by Django 6.0.4 on 2026-04-18 07:02

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('media_id', models.CharField(max_length=255, unique=True)),
                ('media_url', models.URLField(max_length=1000)),
                ('permalink', models.URLField(max_length=1000)),
                ('media_type', models.CharField(max_length=50)),
                ('caption', models.TextField(blank=True, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='authentication.instagramprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('comment_id', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('like_count', models.IntegerField(default=0)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reels.reel')),
            ],
        ),
    ]
